import Footer from '@/components/footer';
import Navbar from '@/components/navbar';
import { Toaster } from '@/components/ui/sonner';
import { geistMono, geistSans } from '@/config/font';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import React from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'WiseWander',
  description: 'Generated by create next app',
};

type Props = { children: React.ReactNode };

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'bg-background min-h-screen font-sans antialiased',
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <div className='relative flex h-screen flex-col gap-16'>
          <Navbar />
          <main className='relative grow'>{children}</main>
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  );
}
